version: "3.8"

services:
  mariadb:
    build:
      context: .
      dockerfile: mariadb.Dockerfile
    container_name: personapp-mariadb
    restart: always
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=persona_db
      - MYSQL_USER=persona_db
      - MYSQL_PASSWORD=persona_db
    networks:
      - personapp-network
    volumes:
      - mariadb_data:/var/lib/mysql
    # healthcheck:  # Temporarily commented out
    #   test: ["CMD", "mysql", "-hlocalhost", "-u$${MYSQL_USER}", "-p$${MYSQL_PASSWORD}", "-e", "SELECT 1"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 10
    #   start_period: 30s

  mongodb:
    build:
      context: .
      dockerfile: mongodb.Dockerfile
    container_name: personapp-mongodb
    restart: always
    ports:
      - "27017:27017"
    command: ["--bind_ip_all"]
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=persona_db
    networks:
      - personapp-network
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'mongosh --host localhost --username root --password root --authenticationDatabase admin --eval "db.adminCommand(''ping'').ok" --quiet',
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  personapp-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: personapp-api
    restart: always
    ports:
      - "3000:3000"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mariadb:
        condition: service_started
      mongodb:
        condition: service_healthy
    networks:
      - personapp-network

networks:
  personapp-network:
    driver: bridge

volumes:
  mariadb_data:
  mongodb_data:
